# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download dependencies
      run: yarn

    - name: Generate Single Page Application
      env:
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        REST_URL: ${{ secrets.REST_URL }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: yarn build

    - name: Generate static site
      env:
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        REST_URL: ${{ secrets.REST_URL }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: yarn generate
